//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoTool.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EchoTool.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Port already in use 的本地化字符串。
        /// </summary>
        internal static string AddressAlreadyInUse {
            get {
                return ResourceManager.GetString("AddressAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not connect to server 的本地化字符串。
        /// </summary>
        internal static string CanNotConnectToServer {
            get {
                return ResourceManager.GetString("CanNotConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reply from {0}, time {1} ms {2} 的本地化字符串。
        /// </summary>
        internal static string ClientResponse {
            get {
                return ResourceManager.GetString("ClientResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection closed by remote party 的本地化字符串。
        /// </summary>
        internal static string ClosedByRemoteParty {
            get {
                return ResourceManager.GetString("ClosedByRemoteParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hostname {0} resolved as {1} 的本地化字符串。
        /// </summary>
        internal static string HostnameResolved {
            get {
                return ResourceManager.GetString("HostnameResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host not found 的本地化字符串。
        /// </summary>
        internal static string HostNotFound {
            get {
                return ResourceManager.GetString("HostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host unreachable 的本地化字符串。
        /// </summary>
        internal static string HostUnreachable {
            get {
                return ResourceManager.GetString("HostUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CORRUPT 的本地化字符串。
        /// </summary>
        internal static string ResponseCorrupt {
            get {
                return ResourceManager.GetString("ResponseCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ResponseOK {
            get {
                return ResourceManager.GetString("ResponseOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response time out 的本地化字符串。
        /// </summary>
        internal static string ResponseTimeout {
            get {
                return ResourceManager.GetString("ResponseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Error 的本地化字符串。
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics: Received={0}, Corrupted={1} 的本地化字符串。
        /// </summary>
        internal static string TCPClientStatistics {
            get {
                return ResourceManager.GetString("TCPClientStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for TCP connection on port {0}. Press any key to exit. 的本地化字符串。
        /// </summary>
        internal static string TCPServerCaption {
            get {
                return ResourceManager.GetString("TCPServerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client {0} accepted at {1} 的本地化字符串。
        /// </summary>
        internal static string TCPServerConnect {
            get {
                return ResourceManager.GetString("TCPServerConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} received [{1}] 的本地化字符串。
        /// </summary>
        internal static string TCPServerDataReceived {
            get {
                return ResourceManager.GetString("TCPServerDataReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session closed by peer. 的本地化字符串。
        /// </summary>
        internal static string TCPSessionClosedByPeer {
            get {
                return ResourceManager.GetString("TCPSessionClosedByPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session timeout. 的本地化字符串。
        /// </summary>
        internal static string TCPSessionTimeout {
            get {
                return ResourceManager.GetString("TCPSessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics: Received={0}, Corupted={1}, Lost={2} 的本地化字符串。
        /// </summary>
        internal static string UDPClientStatistics {
            get {
                return ResourceManager.GetString("UDPClientStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for UDP conncetion on port {0}. Press any key to exit. 的本地化字符串。
        /// </summary>
        internal static string UDPServerCaption {
            get {
                return ResourceManager.GetString("UDPServerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} from {1} received [{2}] 的本地化字符串。
        /// </summary>
        internal static string UDPServerDataReceived {
            get {
                return ResourceManager.GetString("UDPServerDataReceived", resourceCulture);
            }
        }
    }
}
